### ISSUE TITLE
Furnace recipes?

### ISSUE THREAD

**Issue by Kutomi1** [noobanidus/extracobble#3]
It would be really useful if the various cobblestone blocks could be used to craft furnaces (also while mixing them, so by putting multiple types of cobble in the crafting grid), especially if used together with Terraforged, which makes the different types of stones way more common, and it's really a pain that you can't craft furnaces with them.
Of course, I can add my own recipes with a datapack, but I can't make it so you can mix them like I said above. Except if I made every single variation as a different recipe, which is painful to even think about. So if you could add this feature, I'd really appriciate it. (of course, I'm using the datapack that makes the cobble versions actually drop from breaking andesite, granite ect.)

**Comment by noobanidus** [comment]
You should be able to create a tag that contains all of the cobble variants and then just use that for the recipe!

**Comment by Kutomi1** [comment]
Alright. I don't know how to do that, but I'll look into it. Thanks.
